<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>MultiCharacterCampaignTOR.NativeCreation</AssemblyName>
    <RootNamespace>MultiCharacterCampaignTOR.NativeCreation</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony"><HintPath>$(HarmonyDll)</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
