<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>MultiCharacterCampaignTOR.NativeCreation</AssemblyName>
    <RootNamespace>MultiCharacterCampaignTOR.NativeCreation</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
</Project>
