<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>MultiCharacterCampaignTOR</AssemblyName>
    <RootNamespace>MultiCharacterCampaignTOR</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TaleWorlds.Core"><HintPath>$(BannerlordBin)\TaleWorlds.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.CampaignSystem"><HintPath>$(BannerlordBin)\TaleWorlds.CampaignSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.MountAndBlade"><HintPath>$(BannerlordBin)\TaleWorlds.MountAndBlade.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Library"><HintPath>$(BannerlordBin)\TaleWorlds.Library.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Localization"><HintPath>$(BannerlordBin)\TaleWorlds.Localization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.ObjectSystem"><HintPath>$(BannerlordBin)\TaleWorlds.ObjectSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.DotNet"><HintPath>$(BannerlordBin)\TaleWorlds.DotNet.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(HarmonyDll)</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NativeCreation\MultiCharacterCampaignTOR.NativeCreation.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Include="..\RuntimeCompatibility\MultiCharacterCampaignTOR.RuntimeCompatibility.v140.csproj"><Private>false</Private></ProjectReference>
  </ItemGroup>
</Project>