<Project>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <Deterministic>false</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\</OutputPath>

    <!-- Environment variables are automatically exposed as MSBuild properties. -->
    <BannerlordRoot Condition="'$(BannerlordRoot)' == ''">$(BANNERLORD_ROOT)</BannerlordRoot>
    <BannerlordBin Condition="'$(BannerlordBin)' == '' and '$(BannerlordRoot)' != ''">$(BannerlordRoot)\bin\Win64_Shipping_Client</BannerlordBin>
    <TorCoreBin Condition="'$(TorCoreBin)' == '' and '$(BannerlordRoot)' != ''">$(BannerlordRoot)\Modules\TOR_Core\bin\Win64_Shipping_Client</TorCoreBin>
    <HarmonyDll Condition="'$(HarmonyDll)' == '' and '$(MCC_HARMONY_DLL)' != ''">$(MCC_HARMONY_DLL)</HarmonyDll>
    <HarmonyDll Condition="'$(HarmonyDll)' == '' and '$(BannerlordRoot)' != ''">$(BannerlordRoot)\Modules\Bannerlord.Harmony\bin\Win64_Shipping_Client\0Harmony.dll</HarmonyDll>
    <RuntimeHarmonyDll Condition="'$(RuntimeHarmonyDll)' == '' and '$(MCC_RUNTIME_HARMONY_DLL)' != ''">$(MCC_RUNTIME_HARMONY_DLL)</RuntimeHarmonyDll>
    <RuntimeHarmonyDll Condition="'$(RuntimeHarmonyDll)' == ''">$(HarmonyDll)</RuntimeHarmonyDll>
  </PropertyGroup>
</Project>
